### PR TITLE
Complete rework

### PR DESCRIPTION
**Pull request by ffischer42**
Merged all PEN related software packages at MPP. New documentation and several functions have been updated. 
Some HV functions do not work anymore due to a software update of the device.

### CODE REVIEW

**Comment by oschulz** [comment]
Thanks a lot! Just let me know when this is ready to be merged.

**Comment by fhagemann** [comment]
What is the status of this?

**Comment by nVentis** [comment]
Can you give me access to merge+edit pull requests @fhagemann ?

**Comment by fhagemann** [comment]
> Can you give me access to verify changes/merge+edit pull requests @fhagemann ?

I don’t think I have the rights for this, but @oschulz might be able to help us out here.

**Comment by oschulz** [comment]
Try now @nVentis .

**Pull request merged**
