### PR TITLE
Merged all PEN related repositories

### PR DESCRIPTION
**Pull request by ffischer42**

### CODE REVIEW

**Comment by oschulz** [comment]
Is this WIP, or ready for merging?

**Comment by ffischer42** [comment]
There will be some new stuff till this evening. 
I noticed that there is much more to improve in the old code ;-)
I will tell you when I'm done. Thank you!

**Comment by oschulz** [comment]
Ok, I'll mark it as WIP.

**Comment by ffischer42** [comment]
Thanks

**Pull request merged**
